-- Clear existing resources
DELETE FROM resource_favorites;
DELETE FROM resources;

-- Insert new resources from client files
-- Fixed resource types to match frontend expectations (singular forms)
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url, created_at, updated_at) VALUES 
(1, 'Annual Progress Report 2078 79', 'Annual Reports - Annual Progress Report 2078-79.pdf', 'annual-report', 'http://localhost:8080/resources/annual-reports/annual-progress-report-2078-79.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(2, 'Annual Progress Report 2080 81', 'Annual Reports - Annual Progress Report 2080-81.pdf', 'annual-report', 'http://localhost:8080/resources/annual-reports/annual-progress-report-2080-81.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(3, 'Chairperson_Tek Nath Neopane CV', 'BoDs CVs - Chairperson_Tek Nath Neopane CV.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/chairperson_tek-nath-neopane-cv.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(4, 'Copy of DESN Board and Staff', 'BoDs CVs - Copy of DESN-Board-and-Staff.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/copy-of-desn-board-and-staff.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(5, 'Executive Member_Gopal Prasad Ghimire CV', 'BoDs CVs - Executive Member_Gopal Prasad Ghimire CV.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/executive-member_gopal-prasad-ghimire-cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(6, 'Krishna CV', 'BoDs CVs - Krishna CV.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/krishna-cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(7, 'Tika_Bajgain_CV', 'BoDs CVs - Tika_Bajgain_CV.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/tika_bajgain_cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(8, 'Copy of District Adminstration Office Registration_Translation', 'BoDs CVs - Copy of District Adminstration Office Registration_Translation.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/copy-of-district-adminstration-office-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(9, 'Copy of IRD Registration_Translation', 'BoDs CVs - Copy of IRD Registration_Translation.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/copy-of-ird-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(10, 'Copy of Municipality Registration_Translation', 'BoDs CVs - Copy of Municipality Registration_Translation.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/copy-of-municipality-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(11, 'Copy of Social Welfare Council Registrationl_Translation', 'BoDs CVs - Copy of Social Welfare Council Registrationl_Translation.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/copy-of-social-welfare-council-registrationl_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(12, 'District Administration Office Registration', 'BoDs CVs - District Administration Office Registration.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/district-administration-office-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(13, 'Inland Revenue Certificate (PAN)', 'BoDs CVs - Inland Revenue Certificate (PAN).pdf', 'guideline', 'http://localhost:8080/resources/guidelines/inland-revenue-certificate-(pan).pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(14, 'Municipality Registration', 'BoDs CVs - Municipality Registration.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/municipality-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(15, 'NFDN Registration', 'BoDs CVs - NFDN Registration.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/nfdn-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(16, 'Social Welfare Council Registration', 'BoDs CVs - Social Welfare Council Registration.pdf', 'guideline', 'http://localhost:8080/resources/guidelines/social-welfare-council-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(17, 'Communication policy_Disability Empowerment Society Nepal signed', 'DESN Policies - Communication policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-brief', 'http://localhost:8080/resources/policy-briefs/communication-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(18, 'Communication policy_Disability Empowerment Society Nepal', 'DESN Policies - Communication policy_Disability Empowerment Society Nepal.pdf', 'policy-brief', 'http://localhost:8080/resources/policy-briefs/communication-policy_disability-empowerment-society-nepal.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(19, 'Computer policy_Disability Empowerment Society Nepal signed', 'DESN Policies - Computer policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-brief', 'http://localhost:8080/resources/policy-briefs/computer-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(20, 'Computer policy_Disability Empowerment Society Nepal', 'DESN Policies - Computer policy_Disability Empowerment Society Nepal.pdf', 'policy-brief', 'http://localhost:8080/resources/policy-briefs/computer-policy_disability-empowerment-society-nepal.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(21, 'PSEA Policy_Disability Empowerment Society Nepal signed', 'DESN Policies - PSEA Policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-brief', 'http://localhost:8080/resources/policy-briefs/psea-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(22, 'Digital Literacy_Training Manual', 'Publications - Digital Literacy_Training Manual.pdf', 'newsletter', 'http://localhost:8080/resources/newsletters/digital-literacy_training-manual.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(23, 'Local Handicraft_Training Manual', 'Publications - Local Handicraft_Training Manual.pdf', 'newsletter', 'http://localhost:8080/resources/newsletters/local-handicraft_training-manual.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW()),
(24, 'Samadristi Magazine 15th Edition', 'Publications - Samadristi Magazine 15th Edition.pdf', 'newsletter', 'http://localhost:8080/resources/newsletters/samadristi-magazine-15th-edition.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL, NOW(), NOW());