-- Clear existing resources
DELETE FROM resource_favorites;
DELETE FROM resources;

-- Insert new resources from client files
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (1, 'Annual Progress Report 2078 79', 'Annual Reports - Annual Progress Report 2078-79.pdf', 'annual-reports', 'http://localhost:8080/resources/annual-reports/annual-progress-report-2078-79.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (2, 'Annual Progress Report 2080 81', 'Annual Reports - Annual Progress Report 2080-81.pdf', 'annual-reports', 'http://localhost:8080/resources/annual-reports/annual-progress-report-2080-81.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (3, 'Chairperson_Tek Nath Neopane CV', 'BoDs CVs - Chairperson_Tek Nath Neopane CV.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/chairperson_tek-nath-neopane-cv.pdf', 0, TRUE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (4, 'Copy of DESN Board and Staff', 'BoDs CVs - Copy of DESN-Board-and-Staff.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/copy-of-desn-board-and-staff.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (5, 'Executive Member_Gopal Prasad Ghimire CV', 'BoDs CVs - Executive Member_Gopal Prasad Ghimire CV.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/executive-member_gopal-prasad-ghimire-cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (6, 'Krishna CV', 'BoDs CVs - Krishna CV.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/krishna-cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (7, 'Tika_Bajgain_CV', 'BoDs CVs - Tika_Bajgain_CV.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/tika_bajgain_cv.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (8, 'Copy of District Adminstration Office Registration_Translation', 'BoDs CVs - Copy of District Adminstration Office Registration_Translation.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/copy-of-district-adminstration-office-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (9, 'Copy of IRD Registration_Translation', 'BoDs CVs - Copy of IRD Registration_Translation.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/copy-of-ird-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (10, 'Copy of Municipality Registration_Translation', 'BoDs CVs - Copy of Municipality Registration_Translation.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/copy-of-municipality-registration_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (11, 'Copy of Social Welfare Council Registrationl_Translation', 'BoDs CVs - Copy of Social Welfare Council Registrationl_Translation.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/copy-of-social-welfare-council-registrationl_translation.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (12, 'District Administration Office Registration', 'BoDs CVs - District Administration Office Registration.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/district-administration-office-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (13, 'Inland Revenue Certificate (PAN)', 'BoDs CVs - Inland Revenue Certificate (PAN).pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/inland-revenue-certificate-(pan).pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (14, 'Municipality Registration', 'BoDs CVs - Municipality Registration.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/municipality-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (15, 'NFDN Registration', 'BoDs CVs - NFDN Registration.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/nfdn-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (16, 'Social Welfare Council Registration', 'BoDs CVs - Social Welfare Council Registration.pdf', 'guidelines', 'http://localhost:8080/resources/guidelines/social-welfare-council-registration.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (17, 'Communication policy_Disability Empowerment Society Nepal signed', 'DESN Policies - Communication policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-briefs', 'http://localhost:8080/resources/policy-briefs/communication-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (18, 'Communication policy_Disability Empowerment Society Nepal', 'DESN Policies - Communication policy_Disability Empowerment Society Nepal.pdf', 'policy-briefs', 'http://localhost:8080/resources/policy-briefs/communication-policy_disability-empowerment-society-nepal.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (19, 'Computer policy_Disability Empowerment Society Nepal signed', 'DESN Policies - Computer policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-briefs', 'http://localhost:8080/resources/policy-briefs/computer-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (20, 'Computer policy_Disability Empowerment Society Nepal', 'DESN Policies - Computer policy_Disability Empowerment Society Nepal.pdf', 'policy-briefs', 'http://localhost:8080/resources/policy-briefs/computer-policy_disability-empowerment-society-nepal.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (21, 'PSEA Policy_Disability Empowerment Society Nepal signed', 'DESN Policies - PSEA Policy_Disability Empowerment Society Nepal-signed.pdf', 'policy-briefs', 'http://localhost:8080/resources/policy-briefs/psea-policy_disability-empowerment-society-nepal-signed.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (22, 'Digital Literacy_Training Manual', 'Publications - Digital Literacy_Training Manual.pdf', 'newsletters', 'http://localhost:8080/resources/newsletters/digital-literacy_training-manual.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (23, 'Local Handicraft_Training Manual', 'Publications - Local Handicraft_Training Manual.pdf', 'newsletters', 'http://localhost:8080/resources/newsletters/local-handicraft_training-manual.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);
INSERT INTO resources (id, title, description, type, file_url, pages, featured, clicks, favorite_count, publish_date, thumbnail_url) VALUES (24, 'Samadristi Magazine 15th Edition', 'Publications - Samadristi Magazine 15th Edition.pdf', 'newsletters', 'http://localhost:8080/resources/newsletters/samadristi-magazine-15th-edition.pdf', 0, FALSE, 0, 0, '2025-11-10', NULL);